import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UiProvider } from '@/providers/uiProvider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <UiProvider>{children}</UiProvider>
      </body>
    </html>
  )
}
